

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100) NOT NULL UNIQUE,
    senha varchar(100) NOT NULL,
    role varchar (30) NOT NULL,
    habilitado CHAR(1) NOT NULL,
    CONSTRAINT chk_habilitado CHECK (habilitado IN ('S','N'))
);
